apiVersion: v1
kind: ConfigMap
metadata:
  name: costcenter-config
data:
  app.properties: |2+
    quarkus.qpid-jms.url=amqp://<CHANGE_ME>:5672
    quarkus.qpid-jms.username=user
    quarkus.qpid-jms.password=enmasse
    camel.component.kafka.brokers=<CHANGE_ME>:9092